### ISSUE TITLE
epidate python CLI unittest fails when an argument is passed to unittest module

### ISSUE THREAD

**Issue by xsaschako** [DLR-SC/memilio#118]
It's occasionally useful for debugging to pass arguments to the unittest module to e.g. add output, run specific tests, etc. In fact, it may be a good idea to add the `--verbose` argument to the python unittest pipeline in the future. The argument does have the intended effect, additional output is produced. But the epidata unittest `test_cli_correct_default` fails, e.g. this command
```
python -m unittest --verbose
```
causes this failure
```
...
test_cli_correct_default (test_epidata_getDataIntoPandasDataFrame.Test_getDataIntoPandasDataFrame) ... usage: python -m unittest [-h] [-r] [-ff {json,hdf5,json_timeasstring}] [-o OUT_PATH]
python -m unittest: error: unrecognized arguments: --verbose
ERROR
...
ERROR: test_cli_correct_default (test_epidata_getDataIntoPandasDataFrame.Test_getDataIntoPandasDataFrame)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abel_da/epidemiology/pycode/test/test_epidata_getDataIntoPandasDataFrame.py", line 25, in test_cli_correct_default
    [read_data, out_form, out_folder] = gd.cli("spain")
  File "/home/abel_da/epidemiology/pycode/epidemiology/epidata/getDataIntoPandasDataFrame.py", line 181, in cli
    args = parser.parse_args()
  File "/home/abel_da/spack/opt/spack/linux-ubuntu18.04-ivybridge/gcc-9.3.0/python-3.8.5-giziborwsbfygdhmvaz2jcmr7fammj6p/lib/python3.8/argparse.py", line 1771, in parse_args
    self.error(msg % ' '.join(argv))
  File "/home/abel_da/spack/opt/spack/linux-ubuntu18.04-ivybridge/gcc-9.3.0/python-3.8.5-giziborwsbfygdhmvaz2jcmr7fammj6p/lib/python3.8/argparse.py", line 2521, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/home/abel_da/spack/opt/spack/linux-ubuntu18.04-ivybridge/gcc-9.3.0/python-3.8.5-giziborwsbfygdhmvaz2jcmr7fammj6p/lib/python3.8/argparse.py", line 2508, in exit
    _sys.exit(status)
SystemExit: 2
```

As you can see, for some reason a weird mixture of the unittest module help and the epidata help is printed during the test. --verbose is the correct argument for unittest, and it does have the intended effect, `test_cli_correct_default (test_epidata_getDataIntoPandasDataFrame.Test_getDataIntoPandasDataFrame)` is not normally printed.

**Comment by xsaschako** [comment]
The problem is: when called through the unittest module sys.args is loaded with arguments. When calling parser.parse_args() this leads to an exit error. 
A quick fix is:
```
 def setUp(self):
        del sys.argv[1:]
```
This deletes all the arguments, but is certainly not an elegant way to solve this. Maybe someone knows a better way to solve it. Also with this the --verbose argument works just fine.

@dabele

**Comment by dabele** [comment]
not great. I think there should be a way to isolate the test. maybe a subprocess call? It's a test of the CLI anyway, so that may be  appropriate.
