### ISSUE TITLE
Error in getDIVIData

### ISSUE THREAD

**Issue by mknaranja** [DLR-SC/memilio#35]
In

https://github.com/DLR-SC/memilio/blob/a45672fb9b87b7c7acc58020d62723a0fdd08e24/pycode/epidemiology/epidata/getDIVIData.py#L304

I now get

```
Success: Data of date 2021-01-03 has been added to dataframe
Success: Data of date 2021-01-04 has been added to dataframe
Traceback (most recent call last):
  File ".\epidemiology\epidata\getDIVIData.py", line 523, in <module>
    main()
  File ".\epidemiology\epidata\getDIVIData.py", line 519, in main
    get_divi_data(**arg_dict)
  File ".\epidemiology\epidata\getDIVIData.py", line 435, in get_divi_data
    [last_number, df2, new_string] = download_data_for_one_day(last_number, start_date)
  File ".\epidemiology\epidata\getDIVIData.py", line 304, in download_data_for_one_day
    call_string = "date(" + download_date.strftime("%Y, %-m, %-d") + "): " + str(call_number) + "," \
ValueError: Invalid format string
```

I do not really understand why but 

`download_date.strftime("%Y, %m, %d")`

would solve the problem...

**Comment by mknaranja** [comment]
The same applies for line 314.

**Comment by annette-lutz** [comment]
This issue is deprecated since the download of the divi data was restructured in #104.
