### ISSUE TITLE
Memilio-Epidata broken dependency: Twill 3.2 times out while downloading population data. Revert to twill 3.1 by default.

### ISSUE THREAD

**Issue by qacwnfq** [DLR-SC/memilio#820]
### Bug description

Timeouts with twill 3.2. It works with twill 3.1, but my CI pipeline continous to install twill 3.2 when I install epidata.
Therefore, epidata should have its requirements updated.

### Version

Any

### To reproduce

1) use automatic.py, e.g. on commit fedd1f6cfea4e32e41f4b2bbcf02c738279b4682
2) call get_population_data()
3) timeout

### Relevant log output

```zsh
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/opt/conda/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/opt/conda/lib/python3.10/ssl.py", line 1292, in recv
    return self.read(buflen)
  File "/opt/conda/lib/python3.10/ssl.py", line 1165, in read
    return self._sslobj.read(len)
TimeoutError: The read operation timed out
```

### Checklist

- [ ] Attached labels, especially loc:: or model:: labels.
- [ ] Linked to project

**Comment by qacwnfq** [comment]
PR https://github.com/DLR-SC/memilio/pull/821

The pr targets the branch for the autumn data, because this is where the change is required.

**Comment by patricklnz** [comment]
Hi @qacwnfq the twill dependency was already changed in PR #818, see Issue #819. Can this Issue be closed as a duplicate?
